"use client";

import { useEffect, useId, useState } from "react";

/**
 * Renders a Mermaid diagram (state diagram, flowchart, etc.) to inline SVG.
 * Mermaid is dynamically imported so it never runs during SSR and stays out of
 * the initial bundle. securityLevel "strict" sanitizes the generated SVG.
 */
export function Mermaid({ chart }: { chart: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  const rawId = useId();
  const id = "mmd" + rawId.replace(/[^a-zA-Z0-9]/g, "");

  useEffect(() => {
    let active = true;
    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: "base",
          flowchart: { useMaxWidth: true, htmlLabels: true },
          themeVariables: {
            fontFamily: "ui-sans-serif, system-ui, sans-serif",
            fontSize: "14px",
            primaryColor: "#eef2fb",
            primaryBorderColor: "#1B3D7A",
            primaryTextColor: "#1B3D7A",
            lineColor: "#1B3D7A",
            tertiaryColor: "#fdecee",
          },
        });
        const { svg } = await mermaid.render(id, chart.trim());
        if (active) setSvg(svg);
      } catch {
        if (active) setFailed(true);
      }
    })();
    return () => {
      active = false;
    };
  }, [chart, id]);

  if (failed) {
    return (
      <pre className="overflow-x-auto rounded-lg bg-secondary/50 p-3 text-xs leading-relaxed text-muted-foreground">
        {chart.trim()}
      </pre>
    );
  }
  if (!svg) {
    return <div className="h-28 animate-pulse rounded-lg bg-secondary/40" aria-hidden />;
  }
  return (
    <div
      className="mermaid-diagram flex justify-center overflow-x-auto py-1 [&_svg]:h-auto [&_svg]:max-w-full"
      // SVG is generated by Mermaid with securityLevel:"strict" (sanitized).
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
